version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  db-data:
